version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    restart: always

  backend:
    build: ./backend/twitter-tip-bot
    container_name: backend
    ports:
      - "3002:3002"
    restart: always

  proxy:
    build: ./nginx
    container_name: proxy
    ports:
      - "80:80"
    restart: always
