CONSUMER_KEY = "<YOUR_CONSUMER_KEY>"
CONSUMER_SECRET_KEY = "<YOUR_CONSUMER_SECRET_KEY>"
ACCESS_TOKEN = "<YOUR_ACCESS_TOKEN>"
ACCESS_TOKEN_SECRET = "<YOUR_ACCESS_TOKEN_SECRET>"

RPC_URL = "https://guanyu-testnet3-query.bandchain.org"